### ISSUE TITLE
Server Error on Refresh

### ISSUE THREAD

**Issue by bastump987** [ams939/CheckersWebApp#3]
When the client refreshes their browser, it causes the WebSocket connection to be dropped.  The server complains about this, reporting an "Unhandled Error" in CheckersProtocol.  Last line of the stack trace is:

`builtins.AttributeError: 'CheckersProtocol' object has no attribute 'is_closed'`

To reproduce, run the server and the static files server (`cd Client && node index` from project root, may have to run `npm install` if dependencies are missing).  Connect to `http://localhost:8080` and then refresh the page.

**Comment by wonked** [comment]
This was a problem with overriding __init__() for the WebSocketServerProtocol.
So I called super().__init__() to solve this.
