### ISSUE TITLE
Disconnect during own turn bug

### ISSUE THREAD

**Issue by ams939** [ams939/CheckersWebApp#8]
When a player disconnects during their own turn, their opponent is not being disconnected from the match and is stuck waiting for other player (who is no longer there) to finish their turn. Disconnection of opponent during player's own turn is being handled properly however.

**Comment by bastump987** [comment]
Sounds like the client is not receiving a disconnect message from the server in this case.  I'll have to do some testing on the client side to confirm, which I can do either late tonight or early tomorrow.  For now I'd assign to @wonked in case it happens to be a server issue.
